services:
  - type: web
    name: shopmax
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y build-essential libffi-dev python3-dev
      pip install -r requirements.txt
    startCommand: gunicorn app:app